language: node_js

node_js:
  - "8"

cache:
  directories:
    - "node_modules"

services:
  - mysql

install:
  - npm install

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - npm run build
  - npm run test

notifications:
  email: false
